services:
  db:
    image: mysql:8.0
    container_name: mysql-docker
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123!
      TZ: Asia/Seoul
    ports:
      - 3306:3306
    volumes:
      - ./mysql-init/:/docker-entrypoint-initdb.d
    platform: linux/x86_64